####################################
# SpaceChat Configuration          #
# v2                               #
# Written by yakovliam             #
# Visit https://www.yakovliam.com  #
####################################

#=#=#=#=#=#=#=#=#=#=#=#=#
# Storage Configuration #
#                       #
# Storage types:        #
# -> yaml               #
# -> mysql              #
#=#=#=#=#=#=#=#=#=#=#=#=#
storage:
  use: "yaml" # which storage type should we use?
  mysql: # mysql configuration settings
    address: ""
    port: 3306
    username: ""
    password: ""
    database: ""
    use-ssl: false
    verify-server-certificate: false
    tables:
      chat-logs: "spacechat_chatlogs"

#=#=#=#=#=#=#=#=#=#=#=#=#=#
# Redis Configuration     #
#                         #
# This allows multiple    #
# server to have the same #
# chat happening in       #
# realtime!               #
# ----------------------- #
# NOTE: THESE ARE NOT     #
# CHANNELS! THIS IS FOR   #
# MULTI-SERVER SYNC       #
#=#=#=#=#=#=#=#=#=#=#=#=#=#
redis:
  enabled: false
  # Set these server name values to the name of the current server the plugin is present on.
  # For example, if we're running on 'skyblock-1', change the identifier to 'skyblock-1'. This can be accessed
  # through placeholders using %spacechat_server-identifier%
  # The displayName is a display version of the server that can be accessed through placeholders as well by using
  # %spacechat_server-displayname%
  server:
    identifier: "server1"
    displayName: "&a&lServer #1"
  # redis://[password@]host[:port][/databaseNumber]
  # redis-socket:///path/to/socket
  url: "redis://[password@]host[:port][/databaseNumber]"

  # <!> 'chat-channel' and 'broadcast-channel' can ***NOT*** be the same <!>
  # Please choose two different channels
  chat-channel: "spacechat-message"
  broadcast-channel: "spacechat-broadcast"

#=#=#=#=#=#=#=#=#=#=#=#=#
#      Misc Settings    #
#=#=#=#=#=#=#=#=#=#=#=#=#
logging:
  chat:
    log-to-storage: true

broadcast:
  # If enabled, any 'broadcast commands' will broadcast using the wrapper specified
  # in the lang.yml file. If disabled, all broadcasts will default to plain white with
  # no prefixes or suffixes
  use-lang-wrapper: false

item-chat:
  enabled: false
  replace-aliases:
    - "[item]"
    - "{item}"
  with:
    chat: "&7[&f%name% &ox%amount%&7]"
    lore:
      # If enabled, all [item]s in chat will have ONLY the custom lore that is listed below
      use-custom: false
      custom:
        - "&7This is"
        - "&6Custom"
        - "&c&bLore!"

#=#=#=#=#=#=#=#=#=#=#=#=#=#
# Permissions             #
#                         #
# For:                    #
# Using chat colors (&)   #
# Using item chat ([item])#
#=#=#=#=#=#=#=#=#=#=#=#=#=#
permissions:
  use-chat-colors: "space.chat.chatcolor"
  use-item-chat: "space.chat.item-chat"