####################################
# SpaceChat Configuration          #
# v2                               #
# Written by yakovliam             #
# Visit https://www.yakovliam.com  #
####################################

#=#=#=#=#=#=#=#=#=#=#=#=#
# Storage Configuration #
#                       #
# Storage types:        #
# -> sqlite             #
# -> mysql              #
#=#=#=#=#=#=#=#=#=#=#=#=#
storage:
  use: "sqlite" # which storage type should we use?
  mysql: # mysql configuration settings
    address: ""
    port: 3306
    username: ""
    password: ""
    database: ""
    use-ssl: false
    verify-server-certificate: false
    tables:
      chat-logs: "spacechat_chatlogs"
      users: "spacechat_users"
      subscribed-channels: "subscribed_channels"
  sqlite:
    # This generates a file under "plugins/SpaceChat/storage/<database>" where <database> = the config option below
    database: "storage"
    tables:
      chat-logs: "spacechat_chatlogs"
      users: "spacechat_users"
      subscribed-channels: "subscribed_channels"

#=#=#=#=#=#=#=#=#=#=#=#=#=#
# Redis Configuration     #
#                         #
# This allows multiple    #
# server to have the same #
# chat happening in       #
# realtime!               #
# ----------------------- #
# NOTE: THESE ARE NOT     #
# CHANNELS! THIS IS FOR   #
# MULTI-SERVER SYNC       #
#=#=#=#=#=#=#=#=#=#=#=#=#=#
redis:
  enabled: false
  # Set these server name values to the name of the current server the plugin is present on.
  # For example, if we're running on 'skyblock-1', change the identifier to 'skyblock-1'. This can be accessed
  # through placeholders using %spacechat_server-identifier%
  # The displayName is a display version of the server that can be accessed through placeholders as well by using
  # %spacechat_server-displayname%
  server:
    identifier: "server1"
    displayName: "&a&lServer #1"
  # redis://[password@]host[:port][/databaseNumber]
  # redis-socket:///path/to/socket
  url: "redis://[password@]host[:port][/databaseNumber]"

  # <!> 'chat-channel' and 'broadcast-channel' can ***NOT*** be the same <!>
  # Please choose two different channels
  chat-channel: "spacechat-message"
  broadcast-channel: "spacechat-broadcast"

  # This is the key that should be used to define where spacechat looks for a player's current subscribed channels list
  # If you do not know how to configure redis data structures and keys, DO NOT TOUCH THIS VALUE
  player-subscribed-channels-list-key: "spacechat:subscribedchannels:%uuid%:channels"
  player-current-channel-key: "spacechat:channels:%uuid%:current"
  channels-subscribed-uuids-list-key: "spacechat:channels:%channel%"

#=#=#=#=#=#=#=#=#=#=#=#=#
#      Misc Settings    #
#=#=#=#=#=#=#=#=#=#=#=#=#
logging:
  chat:
    log-to-storage: true

broadcast:
  # If enabled, any 'broadcast commands' will broadcast using the wrapper specified
  # in the lang.yml file. If disabled, all broadcasts will default to plain white with
  # no prefixes or suffixes
  use-lang-wrapper: false

item-chat:
  enabled: false
  replace-aliases:
    - "[item]"
    - "{item}"
  with:
    chat: "&7[&f%name% &ox%amount%&7]"
    lore:
      # If enabled, all [item]s in chat will have ONLY the custom lore that is listed below
      use-custom: false
      custom:
        - "&7This is"
        - "&6Custom"
        - "&c&bLore!"
  # This dictates the maximum amount of times that players can use the item-chat feature in a single message
  # Set to -1 to disable the maximum amount
  max-per-message: 2

# Enables or disables relational placeholders
# <!> <!> <!> <!> <!> You can only enable this if your server is [NOT] USING MULTI-SERVER CAPABILITIES (redis, etc) <!> <!> <!> <!> <!> Y
use-relational-placeholders: false

# Enables or disables owner recognition
# No need to change this value as it is set to "true" by default (and forced)
# in every other version of SpaceChat
owner-join: true

#=#=#=#=#=#=#=#=#=#=#=#=#=#
# Permissions             #
#                         #
# For:                    #
# Using chat colors (&)   #
# Using item chat ([item])#
#=#=#=#=#=#=#=#=#=#=#=#=#=#
permissions:
  use-chat-colors: "space.chat.chatcolor"
  use-item-chat: "space.chat.item-chat"