name: SpaceChat
version: @version@
main: dev.spaceseries.spacechat.SpaceChat
authors: [yakovliam]
description: Simple and effective chat formatting
website: https://www.spaceseries.dev/
api-version: 1.13
depend:
  - PlaceholderAPI
